# Generated by Django 5.2.15 on 2026-06-19 16:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dia_inteiro', models.BooleanField(default=True, verbose_name='dia inteiro')),
                ('slots', models.IntegerField(default=0, verbose_name='locais bloqueados')),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'bloqueio',
                'verbose_name_plural': 'bloqueios',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(unique=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('texto', models.TextField()),
                ('imagem_url', models.CharField(blank=True, default='', max_length=255)),
                ('aprovado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'depoimento',
                'verbose_name_plural': 'depoimentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=120)),
                ('telefone_cliente', models.CharField(max_length=40)),
                ('data_evento', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('qtd_horas', models.IntegerField(default=1)),
                ('local_evento', models.CharField(max_length=255)),
                ('itens', models.JSONField(default=list)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mensagem_whatsapp', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Brinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('valor_ate_4h', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor até 4h')),
                ('imagem_url', models.CharField(blank=True, default='', max_length=255, verbose_name='imagem (caminho)')),
                ('destaque', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brinquedos', to='loja.categoria')),
            ],
            options={
                'verbose_name': 'brinquedo',
                'verbose_name_plural': 'brinquedos',
                'ordering': ['-valor_ate_4h'],
            },
        ),
    ]
